# Generated by Django 5.1.2 on 2024-10-13 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
