# Generated by Django 5.1.2 on 2024-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='last_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='last_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
