# Generated by Django 5.1.2 on 2024-10-13 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_speed_ms', models.FloatField(null=True)),
                ('flight_time_seconds', models.IntegerField()),
                ('last_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
